export type DailyLogType = {
  id: string;
  date: string;
  representative: string;
  firstName: string;
  lastName: string;
  dob: string;
  doctorNpName: string;
  lab: 'yes' | 'no';
  labRep: 'yes' | 'no';
  newPatient: boolean;
  enrolled: boolean;
  primaryCarePatient: boolean;
  results: boolean;
  proofOfAddress: boolean;
  insuranceCheck: boolean;
  oneTimeTesting: boolean;
  disenrolled: boolean;
  hivTestNoEnroll: boolean;
  disregardLeft: boolean;
  cashVisit?: string;
  copayAmount?: string;
  copaySource?: string;
  copayReceiptNumber?: string;
  marketingSource?: string;
  nextApptDate?: string;
  adviseCancellationFee?: string;
  adviseProgram?: string;
  providerPrescribed?: string;
  providerPrescriberType?: string;
  providerCloseNote?: string;
  dhFormRep?: string;
  dhFormNumber?: string;
  dhFormElectronic?: string;
  createdAt: string;
  updatedAt: string;
};
