export type DailyLogType = {
  id: string;
  date: string;
  representative: string;
  firstName: string;
  lastName: string;
  dob: string;
  doctorNpName: string;
  lab: 'yes' | 'no';
  labRep: string;
  newPatient: boolean;
  enrolled: boolean;
  proofOfAddress: string;
  eligibilityCheck: string;
  insuranceCheck: string;
  visitType?: string;
  visitServices?: string;
  drOrdered?: string;
  pharmacy?: string;
  cashVisit?: string;
  copayAmount?: string;
  copaySource?: string;
  copayReceiptNumber?: string;
  marketingSource?: string;
  nextApptDate?: string;
  adviseCancellationFee?: string;
  adviseProgram?: string;
  providerPrescribed?: string;
  providerPrescriberType?: string;
  providerCloseNote?: string;
  dhFormRep?: string;
  dhFormNumber?: string;
  dhFormElectronic?: string;
  createdAt: string;
  updatedAt: string;
};
