import type { DataTypes } from "./types";

 

export const Data: DataTypes[] = [
  {
    id: "1",
    name: "Sarah Mitchell",
    rxId: "RX-2401",
    medications: "Lisinopril 10mg",
    quantity: 30,
    dosage: "Once daily",
    refills: 3,
    status: "active",
    nextRefill: "11-25-2025",
  },
  {
    id: "2",
    name: "John Doe",
    rxId: "RX-2402",
    medications: "Metformin 500mg",
    quantity: 60,
    dosage: "Twice daily",
    refills: 0,
    status: "active",
    nextRefill: "12-01-2025",
  },
  {
    id: "3",
    name: "Emily Johnson",
    rxId: "RX-2403",
    medications: "Atorvastatin 20mg",
    quantity: 30,
    dosage: "Once daily",
    refills: 1,
    status: "overdue",
    nextRefill: "01-15-2026",
  },
  {
    id: "4",
    name: "Michael Brown",
    rxId: "RX-2404",
    medications: "Amlodipine 5mg",
    quantity: 90,
    dosage: "Once daily",
    refills: 5,
    status: "due soon",
    nextRefill: "10-10-2025",
  },
  {
    id: "5",
    name: "Jessica Davis",
    rxId: "RX-2405",
    medications: "Levothyroxine 50mcg",
    quantity: 30,
    dosage: "Once daily",
    refills: 2,
    status: "active",
    nextRefill: "11-30-2025",
  },
  {
    id: "6",
    name: "David Wilson",
    rxId: "RX-2406",
    medications: "Omeprazole 20mg",
    quantity: 30,
    dosage: "Once daily",
    refills: 3,
    status: "active",
    nextRefill: "12-15-2025",
  },
  {
    id: "7",
    name: "Sophia Martinez",
    rxId: "RX-2407",
    medications: "Gabapentin 300mg",
    quantity: 60,
    dosage: "Three times daily",
    refills: 1,
    status: "inactive",
    nextRefill: "01-20-2026",
  },
  {
    id: "8",
    name: "James Anderson",
    rxId: "RX-2408",
    medications: "Sertraline 50mg",
    quantity: 30,
    dosage: "Once daily",
    refills: 2,
    status: "active",
    nextRefill: "12-05-2025",
  },
  {
    id: "9",
    name: "Olivia Thomas",
    rxId: "RX-2409",
    medications: "Furosemide 20mg",
    quantity: 30,
    dosage: "Once daily",
    refills: 4,
    status: "due soon",
    nextRefill: "11-20-2025",
  },
  {
    id: "10",
    name: "William Jackson",
    rxId: "RX-2410",
    medications: "Hydrochlorothiazide 25mg",
    quantity: 30,
    dosage: "Once daily",
    refills: 3,
    status: "active",
    nextRefill: "12-10-2025",
  },
  {
    id: "11",
    name: "Isabella White",
    rxId: "RX-2411",
    medications: "Simvastatin 40mg",
    quantity: 30,
    dosage: "Once daily",
    refills: 2,
    status: "inactive",
    nextRefill: "01-25-2026",
  },
  {
    id: "12",
    name: "Ethan Harris",
    rxId: "RX-2412",
    medications: "Citalopram 20mg",
    quantity: 30,
    dosage: "Once daily",
    refills: 1,
    status: "active",
    nextRefill: "12-20-2025",
  },
  {
    id: "13",
    name: "Mia Clark",
    rxId: "RX-2413",
    medications: "Alprazolam 0.5mg",
    quantity: 30,
    dosage: "As needed",
    refills: 5,
    status: "active",
    nextRefill: "11-15-2025",
  },
  {
    id: "14",
    name: "Alexander Lewis",
    rxId: "RX-2414",
    medications: "Tamsulosin 0.4mg",
    quantity: 30,
    dosage: "Once daily",
    refills: 2,
    status: "overdue",
    nextRefill: "12-30-2025",
  },
  {
    id: "15",
    name: "Charlotte Robinson",
    rxId: "RX-2415",
    medications: "Montelukast 10mg",
    quantity: 30,
    dosage: "Once daily",
    refills: 3,
    status: "active",
    nextRefill: "01-10-2026",
  },
];
